function k(b,a,c,d){b.s.Ib(b.mb,a,c,d,void 0)}function l(b,a,c,d){b.s.ma?k(b,a,c,d):b.s.Ce()._OnMessageFromDOM({type:"event",component:b.mb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function n(b,a,c){b.s.D(b.mb,a,c)}function t(b,a){for(const [c,d]of a)n(b,c,d)}function u(b){b.Tb||(b.s.ve(b.Td),b.Tb=!0)}window.Aa=class{constructor(b,a){this.s=b;this.mb=a;this.Tb=!1;this.Td=()=>this.Oa()}ed(){}Oa(){}};function aa(b){-1!==b.cb&&(self.clearTimeout(b.cb),b.cb=-1)}
window.se=class{constructor(b){this.Kc=b;this.Qe=5;this.cb=-1;this.Wb=-Infinity;this.Ud=()=>{this.cb=-1;this.Wb=Date.now();this.rb=!0;this.Kc();this.rb=!1};this.wd=this.rb=!1}j(){aa(this);this.Ud=this.Kc=null}};"use strict";function ba(b,a){n(b,"get-element",c=>{const d=b.ka.get(c.elementId);return a(d,c)})}
window.kf=class extends self.Aa{constructor(b,a){super(b,a);this.ka=new Map;this.Jc=!0;t(this,[["create",()=>{throw Error("required override");}],["destroy",c=>{c=c.elementId;const d=this.ka.get(c);this.Jc&&d.parentElement.removeChild(d);this.ka.delete(c)}],["set-visible",c=>{this.Jc&&(this.ka.get(c.elementId).style.display=c.isVisible?"":"none")}],["update-position",c=>{if(this.Jc){var d=this.ka.get(c.elementId);d.style.left=c.left+"px";d.style.top=c.top+"px";d.style.width=c.width+"px";d.style.height=
c.height+"px";c=c.fontSize;null!==c&&(d.style.fontSize=c+"em")}}],["update-state",c=>{this.ka.get(c.elementId);throw Error("required override");}],["focus",c=>this.Ec(c)],["set-css-style",c=>{const d=this.ka.get(c.elementId),e=c.prop;c=c.val;e.startsWith("--")?d.style.setProperty(e,c):d.style[e]=c}],["set-attribute",c=>{this.ka.get(c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",c=>{this.ka.get(c.elementId).removeAttribute(c.name)}]]);ba(this,c=>c)}Ec(b){var a=this.ka.get(b.elementId);
b.focus?a.focus():a.blur()}};"use strict";const ca=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),v=/android/i.test(navigator.userAgent);let da=0;function w(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.$e?new Promise(c=>{const d="c3_resolve_"+da;++da;self[d]=c;a.textContent=b.df+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}let ea=!1,fa=!1;
function ha(){if(!ea){try{new Worker("blob://",{get type(){fa=!0}})}catch(b){}ea=!0}return fa}let y=new Audio;const ia={"audio/webm; codecs=opus":!!y.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!y.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!y.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!y.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!y.canPlayType("audio/mp4"),"audio/mpeg":!!y.canPlayType("audio/mpeg")};y=null;
async function ja(b){b=await ma(b);return(new TextDecoder("utf-8")).decode(b)}function ma(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const B=[];let D=0;window.RealFile=window.File;const E=[],F=new Map,G=new Map;let na=0;const pa=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");pa.push(b)};const qa=new Set(["cordova","playable-ad","instant-games"]);
let ra=!1;
window.oa=class b{constructor(a){this.ma=a.ff;this.wa=null;this.ba="";this.ab=a.cf;this.Fb={};this.Ua=this.ua=null;this.Rb=[];this.H=this.xa=null;this.Sc=!1;this.Ad=0;this.tb=null;this.$a=-1;this.Ve=()=>this.Je();this.Za=[];this.A=a.Vd;this.Ub="file"===location.protocol.substr(0,4);!this.ma||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&ha()||(this.ma=!1);if("playable-ad"===this.A||"instant-games"===this.A)this.ma=!1;if("cordova"===this.A&&this.ma)if(v){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);c&&
90<=parseInt(c[1],10)||(this.ma=!1)}else this.ma=!1;this.Yb=this.ra=null;"html5"!==this.A||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.D("runtime","cordova-fetch-local-file",c=>this.Fe(c));this.D("runtime","create-job-worker",()=>this.Ge());"cordova"===this.A?document.addEventListener("deviceready",()=>this.pd(a)):this.pd(a)}j(){this.wc();
this.wa&&(this.wa=this.wa.onmessage=null);this.ua&&(this.ua.terminate(),this.ua=null);this.Ua&&(this.Ua.j(),this.Ua=null);this.H&&(this.H.parentElement.removeChild(this.H),this.H=null)}pe(){return ca&&"cordova"===this.A}sc(){const a=navigator.userAgent;return ca&&qa.has(this.A)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}ne(){return v}kd(){return v&&qa.has(this.A)}async pd(a){"macos-wkwebview"===this.A&&this.Hc({type:"ready"});if("playable-ad"===this.A){this.ra=self.c3_base64files;
this.Yb={};await this.ye();for(let d=0,e=a.eb.length;d<e;++d){var c=a.eb[d];this.Yb.hasOwnProperty(c)?a.eb[d]={$e:!0,df:this.Yb[c]}:this.ra.hasOwnProperty(c)&&(a.eb[d]=URL.createObjectURL(this.ra[c]))}}a.bf?this.ba=a.bf:(c=location.origin,this.ba=("null"===c?"file:///":c)+location.pathname,c=this.ba.lastIndexOf("/"),-1!==c&&(this.ba=this.ba.substr(0,c+1)));a.hf&&(this.Fb=a.hf);c=new MessageChannel;this.wa=c.port1;this.wa.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&
window.c3_addPortMessageHandler(d=>this.Ie(d));this.tb=new self.qe(this);await sa(this.tb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.ma?await this.Ee(a,c.port2):await this.De(a,c.port2)}yc(a){a=this.Fb.hasOwnProperty(a)?this.Fb[a]:a.endsWith("/workermain.js")&&this.Fb.hasOwnProperty("workermain.js")?
this.Fb["workermain.js"]:"playable-ad"===this.A&&this.ra.hasOwnProperty(a)?this.ra[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async nc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.A&&this.Ub)return a=await this.Gb(d.Ze?a:this.ab+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),
d)}return new Worker(a,d)}pa(){return Math.max(window.innerWidth,1)}ga(){return Math.max(window.innerHeight,1)}od(a){var c=this.ba,d=location.href,e=this.pa(),f=this.ga(),g=window.devicePixelRatio,h=b.ib(),m=a.qf,q=window.cr_previewImageBlobs||this.ra,p=window.cr_previewProjectFileBlobs,z=window.cr_previewProjectFiles,x=window.nf||"";a=a.Vd;var r=(new URLSearchParams(self.location.search)).has("debug"),A=this.tb;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,
isFullscreen:h,projectData:m,previewImageBlobs:q,previewProjectFileBlobs:p,previewProjectFileSWUrls:z,swClientId:x,exportType:a,isDebug:r,ife:!!self.pf,jobScheduler:{inputPort:A.Rc,outputPort:A.Yc,maxNumWorkers:A.Se},supportedAudioFormats:ia,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.ab+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.ab+"opus.wasm.wasm",isFileProtocol:this.Ub,isiOSCordova:this.pe(),isiOSWebView:this.sc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Ee(a,
c){const d=this.yc(a.gf);"preview"===this.A?(this.ua=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((h,m)=>{const q=p=>{this.ua.removeEventListener("message",q);p.data&&"ok"===p.data.type?h():m()};this.ua.addEventListener("message",q);this.ua.postMessage({type:"construct-worker-init","import":(new URL(d,this.ba)).toString()})})):this.ua=await this.nc(d,this.ba,{type:"module",name:"Runtime",Ze:!0});this.H=document.createElement("canvas");this.H.style.display="none";
const e=this.H.transferControlToOffscreen();document.body.appendChild(this.H);window.c3canvas=this.H;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let f=a.dd||[],g=a.eb;f=await Promise.all(f.map(h=>this.Pa(h)));g=await Promise.all(g.map(h=>this.Pa(h)));if("cordova"===this.A)for(let h=0,m=a.lc.length;h<m;++h){const q=a.lc[h],p=q[0];if(p===a.bd||"scriptsInEvents.js"===p||p.endsWith("/scriptsInEvents.js"))q[1]=await this.Pa(p)}this.ua.postMessage(Object.assign(this.od(a),{type:"init-runtime",
isInWorker:!0,messagePort:c,canvas:e,workerDependencyScripts:f,engineScripts:g,projectScripts:a.lc,mainProjectScript:a.bd,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,e,...ta(this.tb)]);this.Rb=E.map(h=>new h(this));this.nd();ua(this.xa);self.c3_callFunction=(h,m)=>{var q=this.xa;return q.s.md(q.mb,"js-invoke-function",{name:h,params:m},void 0,void 0)};"preview"===this.A&&(self.goToLastErrorScript=()=>this.Ib("runtime","go-to-last-error-script"))}async De(a,c){this.H=document.createElement("canvas");
this.H.style.display="none";document.body.appendChild(this.H);window.c3canvas=this.H;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Rb=E.map(g=>new g(this));this.nd();var d=a.eb.map(g=>"string"===typeof g?(new URL(g,this.ba)).toString():g);Array.isArray(a.dd)&&d.unshift(...a.dd);d=await Promise.all(d.map(g=>this.Pa(g)));await Promise.all(d.map(g=>w(g)));d=self.C3_ProjectScriptsStatus;const e=a.bd,f=a.lc;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.Pa(h),await w(h),"preview"!==
this.A||d[g]||this.rd(g,"main script did not run to completion")}catch(m){this.rd(g,m)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.Pa(h),await w(h);"preview"===this.A&&"object"!==typeof self.jf.lf?(this.Mb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.od(a),
{isInWorker:!1,messagePort:c,canvas:this.H,runOnStartupFunctions:pa}),ua(this.xa),this.qd(),this.Ua=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Ua,a))}rd(a,c){this.Mb();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}qd(){this.Mb()}Mb(){const a=window.Xe;a&&(a.parentElement.removeChild(a),window.Xe=null)}async Ge(){const a=
await va(this.tb);return{outputPort:a,transferables:[a]}}Ce(){if(this.ma)throw Error("not available in worker mode");return this.Ua}Ib(a,c,d,e,f){this.wa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},f)}md(a,c,d,e,f){const g=na++,h=new Promise((m,q)=>{G.set(g,{resolve:m,reject:q})});this.wa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.He(a);
if("result"===c)this.Ke(a);else if("runtime-ready"===c)this.Le();else if("alert-error"===c)this.Mb(),alert(a.message);else if("creating-runtime"===c)this.qd();else throw Error(`unknown message '${c}'`);}He(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=F.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Lb(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.Lb(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,
h);this.Lb(f,!1,""+h)}):this.Lb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Lb(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this.wa.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}Ke(a){const c=a.responseId,d=a.isOk;a=a.result;const e=G.get(c);d?e.resolve(a):e.reject(a);G.delete(c)}D(a,c,d){let e=F.get(a);e||(e=new Map,F.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);
e.set(c,d)}static La(a){if(E.includes(a))throw Error("DOM handler already added");E.push(a)}nd(){for(const a of this.Rb)if("runtime"===a.mb){this.xa=a;return}throw Error("cannot find runtime DOM handler");}Ie(a){this.Ib("debugger","message",a)}Le(){for(const a of this.Rb)a.ed()}static ib(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||ra)}static Nb(a){ra=!!a}ve(a){this.Za.push(a);this.Gc()}Ne(a){a=this.Za.indexOf(a);if(-1===a)throw Error("invalid callback");
this.Za.splice(a,1);this.Za.length||this.wc()}Gc(){-1===this.$a&&this.Za.length&&(this.$a=requestAnimationFrame(this.Ve))}wc(){-1!==this.$a&&(cancelAnimationFrame(this.$a),this.$a=-1)}Je(){this.$a=-1;for(const a of this.Za)a();this.Gc()}Da(a){this.xa.Da(a)}Na(a){this.xa.Na(a)}Fc(){this.xa.Fc()}Kb(a){this.xa.Kb(a)}oe(){return!!ia["audio/webm; codecs=opus"]}async Oe(a){a=await this.md("runtime","opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}te(a){this.Sc=!0;this.Ad=a}me(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||
"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}ld(a){return!this.me(a)}async Pa(a){return"cordova"===this.A&&(a.startsWith("file:")||this.Ub&&this.ld(a))?(a.startsWith(this.ba)&&(a=a.substr(this.ba.length)),a=await this.Gb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Fe(a){const c=a.filename;switch(a.as){case "text":return await this.le(c);case "buffer":return await this.Gb(c);default:throw Error("unsupported type");}}hd(a){const c=window.cordova.file.applicationDirectory+
"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async le(a){a=await this.hd(a);return await ja(a)}xc(){if(B.length&&!(8<=D)){D++;var a=B.shift();this.ze(a.filename,a.ef,a.Ye)}}Gb(a){return new Promise((c,d)=>{B.push({filename:a,ef:e=>{D--;this.xc();c(e)},Ye:e=>{D--;this.xc();d(e)}});this.xc()})}async ze(a,c,d){try{const e=await this.hd(a),f=await ma(e);c(f)}catch(e){d(e)}}Hc(a){if("windows-webview2"===this.A)window.chrome.webview.postMessage(JSON.stringify(a));
else if("macos-wkwebview"===this.A)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a));else throw Error("cannot send wrapper message");}async ye(){const a=[];for(const [c,d]of Object.entries(this.ra))a.push(this.xe(c,d));await Promise.all(a)}async xe(a,c){if("object"===typeof c)this.ra[a]=new Blob([c.str],{type:c.type}),this.Yb[a]=c.str;else{let d=await this.Be(c);d||(d=this.Ae(c));this.ra[a]=d}}async Be(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
c),null}}Ae(a){a=this.Me(a);return this.we(a.data,a.af)}Me(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{af:a,data:d}}we(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,m;for(m=h=0;h<e;++h)g[h]=a.charCodeAt(m++)|a.charCodeAt(m++)<<8|a.charCodeAt(m++)<<16|a.charCodeAt(m++)<<24;for(d&=
3;d--;)f[m]=a.charCodeAt(m),++m;return new Blob([f],{type:c})}};"use strict";const H=self.oa;function wa(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const xa=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),I={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},ya={dispatchUserScriptEvent:!0},J={dispatchRuntimeEvent:!0};
function za(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function Ba(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function K(b){b=URL.createObjectURL(b);try{return await Ba(b)}finally{URL.revokeObjectURL(b)}}
function Ca(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function Da(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await K(b);var d=await Ca(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await K(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await K(b)}
function Ea(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Fa=new Set(["input","textarea","datalist","select"]),Ga=new Set(["canvas","body","html"]);function L(b){Ga.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Ha(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await K(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Da(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Ia=!1;document.addEventListener("pause",()=>Ia=!0);document.addEventListener("resume",()=>Ia=!1);function ua(b){b.zd=!0;b.Vc=b.s.pa();b.ub=b.s.ga()}async function Ja(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Ka(b){return await self.C3_GetSvgImageSize(b.blob)}
function La(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}function Ma(b){self.setTimeout(()=>{b.yd=!0},1E3);"cordova"===b.s.A?(document.addEventListener("pause",()=>Na(b,!0)),document.addEventListener("resume",()=>Na(b,!1))):document.addEventListener("visibilitychange",()=>Na(b,document.hidden));return{isSuspended:!(!document.hidden&&!Ia)}}
function Oa(b){b.td||(b.td=!0,window.addEventListener("deviceorientation",a=>{b.Z||k(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},I)}),window.addEventListener("deviceorientationabsolute",a=>{b.Z||k(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},I)}))}
function Pa(b){b.sd||(b.sd=!0,window.addEventListener("devicemotion",a=>{if(!b.Z){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});k(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},I)}}))}async function Qa(b){await za(b.url)}
function Ra(b,a){b.Bd=a.message;-1===b.Nc&&(b.Nc=setTimeout(()=>{b.Nc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.Bd)},250))}function M(b){if(!b.Z){var a=H.ib();a&&"any"!==b.$c&&Sa(b);k(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.pa(),innerHeight:b.ga()})}}function Ta(b,a){console.warn("[Construct] Fullscreen request failed: ",a);k(b,"fullscreenerror",{isFullscreen:H.ib(),innerWidth:b.pa(),innerHeight:b.ga()})}
function Na(b,a){a?b.s.wc():b.s.Gc();k(b,"visibilitychange",{hidden:a})}function Ua(b,a,c){"Backspace"===c.key&&L(c);if(!b.Z){var d=xa.get(c.code)||c.code;l(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},I)}}
function Va(b,a,c,d){b.Z||wa(c)||l(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.ca,pageX:c.pageX,pageY:c.pageY+b.ca,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}function Wa(b){window!==window.top&&window.focus();Xa(b.target)&&document.activeElement&&!Xa(document.activeElement)&&document.activeElement.blur()}
function N(b,a,c){if(!b.Z){if(b.Cb&&"pointermove"!==a){var d=b.Cb;d.rb||(aa(d),d.Wb=Date.now())}d=0;"mouse"===c.pointerType&&(d=b.zb);l(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.ca,pageX:c.pageX,pageY:c.pageY+b.ca,movementX:(c.movementX||0)+b.ec,movementY:(c.movementY||0)+b.fc,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||
0,twist:c.twist||0,timeStamp:c.timeStamp},I);b.ec=0;b.fc=0;"mouse"===c.pointerType&&(d="mousemove","pointerdown"===a?d="mousedown":"pointerup"===a&&(d="mouseup"),Va(b,d,c,ya),b.zb=c.buttons)}}
function Ya(b,a,c){if(!b.Z&&!wa(c)){var d=b.zb;"pointerdown"===a&&0!==d?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");l(b,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.ca,pageX:c.pageX,pageY:c.pageY+b.ca,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},I);b.zb=c.buttons;Va(b,c.type,c,ya)}}
function O(b,a,c){if(!b.Z)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];l(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+b.ca,pageX:f.pageX,pageY:f.pageY+b.ca,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},
I)}}function Za(b,a,c){document.body.style.transform="";b.ca=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,b.ca=a))}}function $a(b,a,c,d){const e=b.pa(),f=b.ga();b.bb=-1;e!=a||f!=c?k(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:H.ib()}):10>d&&ab(b,e,f,d+1)}
function ab(b,a,c,d){-1!==b.bb&&clearTimeout(b.bb);b.bb=setTimeout(()=>$a(b,a,c,d),48)}
function Sa(b){b=b.$c;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function Xa(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
H.La(class extends self.Aa{constructor(b){super(b,"runtime");this.Gd=!0;this.zd=!1;this.bb=-1;this.$c="any";this.sd=this.td=!1;this.Ga=null;this.Z=!1;this.Bd="";this.Nc=-1;this.Ta=this.Cb=null;this.fc=this.ec=0;this.yd=!1;this.Vc=b.pa();this.ub=b.ga();this.ca=this.Eb=0;b.D("canvas","update-size",d=>{var e=this.s;e.Sc||(e=e.H,e.style.width=d.styleWidth+"px",e.style.height=d.styleHeight+"px",e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",document.documentElement.style.setProperty("--construct-scale",
d.displayScale),this.Gd&&(e.style.display="",this.Gd=!1))});b.D("runtime","invoke-download",d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=e;f.download=d;g.appendChild(f);f.click();g.removeChild(f)});b.D("runtime","raster-svg-image",d=>Ja(d));b.D("runtime","get-svg-image-size",d=>Ka(d));b.D("runtime","set-target-orientation",d=>{this.$c=d.targetOrientation});b.D("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.D("runtime",
"post-to-debugger",d=>La(d));b.D("runtime","go-to-script",d=>La(d));b.D("runtime","before-start-ticking",()=>Ma(this));b.D("runtime","debug-highlight",d=>{if(d.show){this.Ga||(this.Ga=document.createElement("div"),this.Ga.id="inspectOutline",document.body.appendChild(this.Ga));var e=this.Ga;e.style.display="";e.style.left=d.left-1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.Ga&&(this.Ga.style.display="none")});b.D("runtime",
"enable-device-orientation",()=>Oa(this));b.D("runtime","enable-device-motion",()=>Pa(this));b.D("runtime","add-stylesheet",d=>Qa(d));b.D("runtime","script-create-worker",d=>{const e=d.port2;(new Worker(d.url,d.opts)).postMessage({type:"construct-worker-init",port2:e},[e])});b.D("runtime","alert",d=>this.Bc(d));b.D("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.D("runtime","set-exporting-to-video",d=>{this.Z=!0;const e=document.createElement("h1");
e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.s.H.style.display="";this.s.te(d.duration)});b.D("runtime","export-to-video-progress",d=>Ra(this,d));b.D("runtime","exported-to-video",d=>{window.We({type:"exported-video",blob:d.blob,time:d.time})});b.D("runtime","exported-to-image-sequence",d=>{window.We({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time,gif:d.gif})});const a=new Set(["input","textarea","datalist"]);
window.addEventListener("contextmenu",d=>{const e=d.target;a.has(e.tagName.toLowerCase())||Ea(e)||d.preventDefault()});const c=b.H;window.addEventListener("selectstart",L);window.addEventListener("gesturehold",L);c.addEventListener("selectstart",L);c.addEventListener("gesturehold",L);window.addEventListener("touchstart",L,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",L,{passive:!1}),c.addEventListener("pointerdown",L)):c.addEventListener("touchstart",L);this.zb=
0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",Ha,{passive:!1});window.addEventListener("wheel",Ha,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.Z&&this.zd){var d=this.pa();var e=this.ga();if(this.s.kd()){if(this.yd){if(this.Vc===d&&e<this.ub){this.Eb=this.ub-e;Za(this,this.ub,this.Eb);d=void 0;break a}0<this.Eb&&(this.Eb=0,Za(this,e,this.Eb))}this.Vc=d;this.ub=e}k(this,"window-resize",{innerWidth:d,innerHeight:e,
devicePixelRatio:window.devicePixelRatio,isFullscreen:H.ib()});this.s.sc()&&(-1!==this.bb&&clearTimeout(this.bb),$a(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>M(this));window.addEventListener("webkitfullscreenchange",()=>M(this));window.addEventListener("mozfullscreenchange",()=>M(this));window.addEventListener("fullscreenerror",d=>Ta(this,d));window.addEventListener("webkitfullscreenerror",d=>Ta(this,d));window.addEventListener("mozfullscreenerror",d=>Ta(this,
d));if(b.sc())if(window.visualViewport){let d=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var d=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):Ea(f)}else d=!1}d||(document.scrollingElement.scrollTop=
0)});self.C3WrapperOnMessage=d=>{"entered-fullscreen"===d?(H.Nb(!0),M(this)):"exited-fullscreen"===d?(H.Nb(!1),M(this)):console.warn("Unknown wrapper message: ",d)};this.Va=new Set;this.$b=new WeakSet;this.va=!1}ed(){window.addEventListener("focus",()=>{k(this,"window-focus",null,J)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=!1}k(this,"window-blur",{parentHasFocus:a},J);this.zb=0});window.addEventListener("focusin",a=>{a=a.target;(Fa.has(a.tagName.toLowerCase())||
Ea(a))&&k(this,"keyboard-blur",null,J)});window.addEventListener("keydown",a=>Ua(this,"keydown",a));window.addEventListener("keyup",a=>Ua(this,"keyup",a));window.addEventListener("dblclick",a=>Va(this,"dblclick",a,I));window.addEventListener("wheel",a=>{this.Z||k(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.ca,pageX:a.pageX,pageY:a.pageY+this.ca,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},I)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
a=>{Wa(a);N(this,"pointerdown",a)}),this.s.ma&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.Cb=new self.se(()=>{N(this,"pointermove",this.Ta);this.Ta=null}),this.Cb.wd=!0,window.addEventListener("pointerrawupdate",a=>{this.Ta&&(this.ec+=this.Ta.movementX||0,this.fc+=this.Ta.movementY||0);this.Ta=a;a=this.Cb;if(-1===a.cb){var c=Date.now(),d=c-a.Wb,e=a.Qe;d>=e&&a.wd?(a.Wb=c,a.rb=!0,a.Kc(),a.rb=!1):a.cb=self.setTimeout(a.Ud,Math.max(e-d,4))}})):window.addEventListener("pointermove",
a=>N(this,"pointermove",a)),window.addEventListener("pointerup",a=>N(this,"pointerup",a)),window.addEventListener("pointercancel",a=>N(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{Wa(a);Ya(this,"pointerdown",a)}),window.addEventListener("mousemove",a=>Ya(this,"pointermove",a)),window.addEventListener("mouseup",a=>Ya(this,"pointerup",a)),window.addEventListener("touchstart",a=>{Wa(a);O(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>O(this,"pointermove",a)),window.addEventListener("touchend",
a=>O(this,"pointerup",a)),window.addEventListener("touchcancel",a=>O(this,"pointercancel",a)));const b=()=>this.Fc();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0);this.s.ne()&&!this.s.kd()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{Za(this,this.ga(),
navigator.virtualKeyboard.boundingRect.height)}))}pa(){return this.s.pa()}ga(){return this.s.ga()}Fc(){var b=[...this.Va];this.Va.clear();if(!this.va)for(const a of b)(b=a.play())&&b.catch(()=>{this.$b.has(a)||this.Va.add(a)})}Da(b){if("function"!==typeof b.play)throw Error("missing play function");this.$b.delete(b);let a;try{a=b.play()}catch(c){this.Va.add(b);return}a&&a.catch(()=>{this.$b.has(b)||this.Va.add(b)})}Na(b){this.Va.delete(b);this.$b.add(b)}Kb(b){this.va=!!b}Bc(b){alert(b.message)}});
"use strict";async function sa(b){if(b.Pe)throw Error("already initialised");b.Pe=!0;var a=b.ya.yc(("playable-ad"===b.ya.A?b.ya.ab:"")+"dispatchworker.js");b.Mc=await b.ya.nc(a,b.lb,{name:"DispatchWorker"});a=new MessageChannel;b.Rc=a.port1;b.Mc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Yc=await va(b)}function ta(b){return[b.Rc,b.Yc]}
async function va(b){const a=b.Hd.length;var c=b.ya.yc(("playable-ad"===b.ya.A?b.ya.ab:"")+"jobworker.js");c=await b.ya.nc(c,b.lb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Mc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.Hd.push(c);return e.port1}
self.qe=class{constructor(b){this.ya=b;this.lb=b.ba;this.lb="preview"===b.A?this.lb+"workers/":this.lb+b.ab;this.Se=Math.min(navigator.hardwareConcurrency||2,16);this.Mc=null;this.Hd=[];this.Yc=this.Rc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.oa({ff:!1,gf:"workermain.js",eb:["scripts/c3runtime.js"],lc:[],bd:"",cf:"scripts/",dd:[],Vd:"html5"}));"use strict";const bb=180/Math.PI;
async function cb(b,a){if(a.isiOSCordova||a.isSafari)b.cc=!0;b.ad=a.timeScaleMode;b.Md=["equalpower","HRTF","soundfield"][a.panningModel];b.xd=["linear","inverse","exponential"][a.distanceModel];b.Nd=a.refDistance;b.Ld=a.maxDistance;b.Pd=a.rolloffFactor;if(b.s.Sc)b.cc=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.s.Ad)});else{var c={latencyHint:a.latencyHint};b.Sd||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");db(b);b.g.onstatechange=()=>{"running"!==b.g.state&&db(b);k(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Ra=b.g.createGain();b.Ra.connect(b.g.destination);c=a.listenerPos;b.aa[0]=c[0];b.aa[1]=c[1];b.aa[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>
P(b,d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function eb(b,a){var c=a.originalUrl;const d=a.url,e=a.type,f=a.isMusic,g=a.tag,h=a.isLooping,m=a.vol,q=a.pos,p=a.panning,z=a.stereoPan;let x=a.off;0<x&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),x=x-a.performanceTime/1E3+a.contextTime):x=x-performance.now()/1E3+b.g.currentTime);b.Id=g;gb(b,g);try{b.$=await hb(b,c,d,e,g,f);if(p){Q(b.$,!0);var r=b.$,A=p.innerAngle,ka=p.outerAngle,la=p.outerGain;if(r.sb){ib(r,p.x,p.y,p.angle);var C=self.fb.ue;r.sa[0]!==C(A)&&(r.sa[0]=C(A),
r.F.coneInnerAngle=C(A));r.sa[1]!==C(ka)&&(r.sa[1]=C(ka),r.F.coneOuterAngle=C(ka));r.sa[2]!==la&&(r.sa[2]=la,r.F.coneOuterGain=la)}p.hasOwnProperty("uid")&&(b.$.qa=p.uid)}else"number"===typeof z&&0!==z?(R(b.$,!0),jb(b.$,z)):(Q(b.$,!1),R(b.$,!1));b.$.Play(h,m,q,x)}catch(wb){console.error("[Construct] Audio: error starting playback: ",wb);return}finally{c=b.Bb.get(g);if(!c)throw Error("expected pending tag");c.cd--;0===c.cd&&(c.resolve(),b.Bb.delete(g))}u(b)}
async function kb(b,a){var c=a.tag;const d=a.vol,e=a.duration;a=a.stopOnEnd;await lb(b,c);for(const p of S(b,c)){c=p;var f=d,g=e,h=a;if(!c.Sa){var m=c.G.gain;m.cancelScheduledValues(0);var q=c.u.g.currentTime;g=q+g;m.setValueAtTime(m.value,q);m.linearRampToValueAtTime(f,g);c.Ka=f;c.pb=g;c.Rd=h}}T(b)}async function mb(b,a){const c=a.tag;a=a.rate;await lb(b,c);for(const d of S(b,c))b=d,b.la!==a&&(b.la=a,b.Ea())}
async function nb(b,a){const c=a.tag;a=a.pos;await lb(b,c);for(const d of S(b,c))d.tc(a)}async function ob(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await hb(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function pb(b,a){if(a=await P(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.ia.indexOf(a),-1!==a&&b.ia.splice(a,1)}
async function qb(b,a){var c=a.type,d=a.tag,e=a.params;if("filter"===c)e=new self.ae(b,...e);else if("delay"===c)e=new self.Zd(b,...e);else if("convolution"===c){c=null;try{c=await P(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(g){console.log("[Construct] Audio: error loading convolution: ",g);return}c=e=new self.Yd(b,c.ha,...e);var f=a.bufferType;c.ud=a.bufferOriginalUrl;c.vd=f}else if("flanger"===c)e=new self.be(b,...e);else if("phaser"===c)e=new self.de(b,...e);else if("gain"===c)e=
new self.ce(b,...e);else if("stereopan"===c)e=new self.fe(b,...e);else if("tremolo"===c)e=new self.ge(b,...e);else if("ringmod"===c)e=new self.ee(b,...e);else if("distortion"===c)e=new self.$d(b,...e);else if("compressor"===c)e=new self.Xd(b,...e);else if("analyser"===c)e=new self.Wd(b,...e);else throw Error("invalid effect type");a=e;d=d.toLowerCase();e=b.ja.get(d);e||(e=[],b.ja.set(d,e));a.Fd=e.length;a.ea=d;e.push(a);rb(b,d);sb(b)}
async function tb(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(const e of b.J)e.Ba()&&1===c||!e.Ba()&&2===c?d.push(e):e.j();b.J=d}for(const e of b.ja.values())for(const f of e)f.j();b.ja.clear();b.jc=a.timeScale;b.Oc=a.gameTime;d=a.listenerPos;b.aa[0]=d[0];b.aa[1]=d[1];b.aa[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);b.va=a.isSilent;b.s.Kb(b.va);b.Zb=a.masterVolume;b.Ra.gain.value=b.Zb;d=[];for(const e of Object.values(a.effects))d.push(Promise.all(e.map(f=>qb(b,f))));await Promise.all(d);
await Promise.all(a.playing.map(e=>ub(b,e,c)));T(b)}async function vb(b,a){try{const c=b.g.suspend(a.time);b.Ed?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.s.Ib("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>xb(d)),b.Ed=!0);await c}catch(c){xb(c)}}
function db(b){b.Sb||(b.Qc=!1,window.addEventListener("pointerup",b.za,!0),window.addEventListener("touchend",b.za,!0),window.addEventListener("click",b.za,!0),window.addEventListener("keydown",b.za,!0),b.Sb=!0)}
async function P(b,a,c,d,e,f){for(var g of b.ia)if(g.hb()===c)return await yb(g),g;if(f)return null;if(e&&(b.cc||b.Dd)){f=0;for(let h=0,m=b.ia.length;h<m;++h)g=b.ia[h],b.ia[f]=g,g.Ba()?g.j():++f;b.ia.length=f}f="audio/webm; codecs=opus"===d&&!b.Sd;e&&f&&(b.Dd=!0);c=!e||b.cc||f?new self.je(b,a,c,d,e,f):new self.he(b,a,c,d,e);b.ia.push(c);await yb(c);b.Kd.has(a)||(k(b,"buffer-metadata",{originalUrl:a,duration:c.fa()}),b.Kd.add(a));return c}
function zb(b,a){return(a=b.ja.get(a.toLowerCase()))?a[0].N():b.na()}function rb(b,a){let c=b.na();var d=b.ja.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.S(b.na()):e.S(d[f+1].N())}}for(const f of S(b,a))d=c,e=f.da||f.F||f.G,e.disconnect(),e.connect(d);b.Ha&&b.Wc===a&&(b.Ha.disconnect(),b.Ha.connect(c))}
function*S(b,a){if(a)for(const c of b.J)b=c.ea,(b.length!==a.length?0:b===a||b.toLowerCase()===a.toLowerCase())&&(yield c);else b.$&&!b.$.U()&&(yield b.$)}function Ab(b,a,c){return c?b.s.Oe(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Bb(b,a){let c=0;for(let d=0,e=b.J.length;d<e;++d){const f=b.J[d];b.J[c]=f;f.O===a?f.j():++c}b.J.length=c}
async function hb(b,a,c,d,e,f){for(const g of b.J)if(g.hb()===c&&(g.mc()||f))return g.ea=e,g;a=await P(b,a,c,d,f);e="html5"===a.Ic?new self.ie(a.u,a,e):new self.ke(a.u,a,e);b.J.push(e);return e}function gb(b,a){let c=b.Bb.get(a);if(!c){let d=null;c={cd:0,promise:new Promise(e=>d=e),resolve:d};b.Bb.set(a,c)}c.cd++}function lb(b,a){a||(a=b.Id);return(b=b.Bb.get(a))?b.promise:Promise.resolve()}function T(b){if(0<b.Qa.size)u(b);else for(const a of b.J)if(!a.I&&!a.U()){u(b);break}}
function Cb(b,a,c,d){k(b,"trigger",{type:a,tag:c,aiid:d})}function sb(b){b.Tc||(b.Tc=!0,Promise.resolve().then(()=>Db(b)))}function Db(b){const a={};for(const [c,d]of b.ja)a[c]=d.map(e=>e.gb());k(b,"fxstate",{fxstate:a});b.Tc=!1}
async function ub(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tag,m=a.isLooping,q=a.volume,p=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await hb(b,d,e,f,h,g)}catch(z){console.error("[Construct] Audio: error loading audio state: ",z);return}b=c;(d=a.pan)?(Q(b,!0),e=b.F,f=d.pos,b.Xa[0]=f[0],b.Xa[1]=f[1],b.Xa[2]=f[2],f=d.orient,b.Wa[0]=f[0],b.Wa[1]=f[1],b.Wa[2]=f[2],e.setPosition(...b.Xa),e.setOrientation(...b.Wa),b.sa[0]=d.cia,b.sa[1]=d.coa,b.sa[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.qa=d.uid):Q(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?R(b,!1):(R(b,!0),jb(b,d));c.Play(m,q,p,0);a.isPlaying||c.jb();c.Ac(a)}}}function xb(b){console.error("[Audio] Offline rendering error: ",b)}
self.fb=class extends self.Aa{constructor(b){super(b,"audio");this.Ra=this.g=null;this.Sb=this.Qc=!1;this.za=()=>{if(!this.Qc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Sb&&(this.Qc=!0,window.removeEventListener("pointerup",this.za,!0),window.removeEventListener("touchend",this.za,!0),window.removeEventListener("click",this.za,!0),window.removeEventListener("keydown",
this.za,!0),this.Sb=!1)}};this.ia=[];this.J=[];this.$=null;this.Id="";this.Kd=new Set;this.Jd=-1;this.Bb=new Map;this.Zb=1;this.va=!1;this.ad=0;this.jc=1;this.Oc=0;this.Md="HRTF";this.xd="inverse";this.Nd=600;this.Ld=1E4;this.Pd=1;this.aa=[0,0,0];this.Dd=this.cc=!1;this.Sd=this.s.oe();this.ja=new Map;this.Qa=new Set;this.Ed=this.Tc=!1;this.Wc="";this.Ha=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Ha&&this.Ha.disconnect();this.Wc=c.toLowerCase();this.Ha=this.g.createMediaStreamSource(a);this.Ha.connect(zb(this,
this.Wc))};this.Qb=null;self.C3Audio_GetOutputStream=()=>{this.Qb||(this.Qb=this.g.createMediaStreamDestination(),this.Ra.connect(this.Qb));return this.Qb.stream};self.C3Audio_DOMInterface=this;t(this,[["create-audio-context",a=>cb(this,a)],["play",a=>eb(this,a)],["stop",a=>{a=a.tag;for(const c of S(this,a))c.Ca()}],["stop-all",()=>{for(const a of this.J)a.Ca()}],["set-paused",a=>{const c=a.tag;a=a.paused;for(const d of S(this,c))a?d.jb():d.Jb();T(this)}],["set-volume",a=>{const c=a.tag;a=a.vol;for(const d of S(this,
c))U(d,a)}],["fade-volume",a=>kb(this,a)],["set-master-volume",a=>{this.Zb=a.vol;this.Ra.gain.value=this.Zb}],["set-muted",a=>{const c=a.tag;a=a.isMuted;for(const d of S(this,c))Eb(d,a)}],["set-silent",a=>{this.va=a.isSilent;this.s.Kb(this.va);for(const c of this.J)c.Ob()}],["set-looping",a=>{const c=a.tag;a=a.isLooping;for(const d of S(this,c))d.uc(a)}],["set-playback-rate",a=>mb(this,a)],["set-stereo-pan",a=>{const c=a.tag;a=a.p;for(const d of S(this,c))R(d,!0),jb(d,a)}],["seek",a=>nb(this,a)],
["preload",a=>ob(this,a)],["unload",a=>pb(this,a)],["unload-all",()=>{for(const a of this.ia)a.j();this.ia.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.J)c.vc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>qb(this,a)],["set-effect-param",a=>{const c=a.index,d=a.param,e=a.value,f=a.ramp,g=a.time;a=this.ja.get(a.tag);!a||0>c||c>=a.length||(a[c].Y(d,e,f,g),sb(this))}],["remove-effects",a=>{a=a.tag.toLowerCase();const c=this.ja.get(a);
if(c&&c.length){for(const d of c)d.j();this.ja.delete(a);rb(this,a)}}],["tick",a=>{this.jc=a.timeScale;this.Oc=a.gameTime;this.Jd=a.tickCount;if(0!==this.ad)for(var c of this.J)c.Ea();!(c=a.listenerPos)||this.aa[0]===c[0]&&this.aa[1]===c[1]&&this.aa[2]===c[2]||(this.aa[0]=c[0],this.aa[1]=c[1],this.aa[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));for(const d of a.instPans){a=d.uid;for(const e of this.J)e.qa===a&&ib(e,d.x,d.y,d.angle)}}],["load-state",a=>tb(this,a)],["offline-render-audio",a=>
vb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}V(){return this.g}na(){return this.Ra}Hb(){return this.va}Da(b){this.s.Da(b)}Na(b){this.s.Na(b)}Oa(){for(var b of this.Qa)b.Oa();b=this.g.currentTime;for(var a of this.J)a.Oa(b);a=this.J.filter(c=>!c.I&&!c.U()).map(c=>c.gb());k(this,"state",{tickCount:this.Jd,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Qa].map(c=>({tag:c.ea,index:c.Fd,peak:c.Ya,rms:c.Od,binCount:c.l.frequencyBinCount,freqBins:c.Cd}))});0===
a.length&&0===this.Qa.size&&this.Tb&&(this.s.Ne(this.Td),this.Tb=!1)}static ue(b){return b*bb}static jd(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static re(b){return Math.log(Math.max(Math.min(b,1),0))/Math.log(10)*20}};self.oa.La(self.fb);"use strict";function yb(b){b.Xb||(b.Xb=b.zc());return b.Xb}self.fd=class{constructor(b,a,c,d,e){this.u=b;this.Ue=a;this.Ja=c;this.R=d;this.Re=e;this.Ic="";this.Xb=null}j(){this.Xb=this.u=null}zc(){}V(){return this.u.V()}pc(){return this.Ue}hb(){return this.Ja}oc(){return this.R}Ba(){return this.Re}fa(){}};
"use strict";
self.he=class extends self.fd{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Ic="html5";this.M=new Audio;this.M.crossOrigin="anonymous";this.M.autoplay=!1;this.M.preload="auto";this.vb=this.wb=null;this.M.addEventListener("canplaythrough",()=>!0);this.Ab=this.V().createGain();this.yb=null;this.M.addEventListener("canplay",()=>{this.wb&&(this.wb(),this.vb=this.wb=null);!this.yb&&this.M&&(this.yb=this.V().createMediaElementSource(this.M),this.yb.connect(this.Ab))});this.onended=null;this.M.addEventListener("ended",()=>
{if(this.onended)this.onended()});this.M.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Ja}' error: `,f);this.vb&&(this.vb(f),this.vb=this.wb=null)})}j(){Bb(this.u,this);this.Ab.disconnect();this.Ab=null;this.yb.disconnect();this.yb=null;this.M&&!this.M.paused&&this.M.pause();this.M=this.onended=null;super.j()}zc(){return new Promise((b,a)=>{this.wb=b;this.vb=a;this.M.src=this.Ja})}T(){return this.M}fa(){return this.M.duration}};"use strict";
async function Fb(b){if(b.Fa)return b.Fa;var a=b.u.s;if("cordova"===a.A&&a.ld(b.Ja)&&a.Ub)b.Fa=await a.Gb(b.Ja);else{a=await fetch(b.Ja);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Fa=await a.arrayBuffer()}}async function Gb(b){if(b.ha)return b.ha;b.ha=await Ab(b.u,b.Fa,b.Te);b.Fa=null}
self.je=class extends self.fd{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Ic="webaudio";this.ha=this.Fa=null;this.Te=!!f}j(){Bb(this.u,this);this.ha=this.Fa=null;super.j()}async zc(){try{await Fb(this),await Gb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Ja}': `,b)}}fa(){return this.ha?this.ha.duration:0}};"use strict";let Hb=0;
function Q(b,a){a=!!a;b.sb!==a&&(b.sb=a,b.sb?(R(b,!1),b.F||(b.F=b.V().createPanner(),b.F.panningModel=b.u.Md,b.F.distanceModel=b.u.xd,b.F.refDistance=b.u.Nd,b.F.maxDistance=b.u.Ld,b.F.rolloffFactor=b.u.Pd),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.na())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.na())))}
function R(b,a){a=!!a;b.Vb!==a&&(b.Vb=a,b.Vb?(Q(b,!1),b.da=b.V().createStereoPanner(),b.G.disconnect(),b.G.connect(b.da),b.da.connect(b.na())):(b.da.disconnect(),b.da=null,b.G.disconnect(),b.G.connect(b.na())))}function jb(b,a){b.Vb&&b.Zc!==a&&(b.da.pan.value=a,b.Zc=a)}function U(b,a){b.Ka=a;b.G.gain.cancelScheduledValues(0);b.pb=-1;b.G.gain.value=b.qc()}function Eb(b,a){a=!!a;b.Sa!==a&&(b.Sa=a,b.Ob())}
function ib(b,a,c,d){if(b.sb){var e=b.Xa,f=b.Wa,g=Math.cos(d);d=Math.sin(d);if(e[0]!==a||e[1]!==c||0!==e[2])e[0]=a,e[1]=c,e[2]=0,b.F.setPosition(...e);if(f[0]!==g||f[1]!==d||0!==f[2])f[0]=g,f[1]=d,f[2]=0,b.F.setOrientation(...f)}}function V(b){return b.Uc?b.u.Oc:performance.now()/1E3}
self.gd=class{constructor(b,a,c){this.u=b;this.O=a;this.ea=c;this.Pb=Hb++;this.G=this.V().createGain();this.G.connect(this.na());this.F=null;this.sb=!1;this.Xa=[0,0,0];this.Wa=[0,0,0];this.sa=[0,0,0];this.da=null;this.Vb=!1;this.Zc=0;this.I=!0;this.X=this.ta=this.K=!1;this.Ka=1;this.Sa=!1;this.la=1;b=this.u.ad;this.Uc=1===b&&!this.Ba()||2===b;this.pb=this.qa=-1;this.Rd=!1}j(){this.O=this.u=null;this.F&&(this.F.disconnect(),this.F=null);this.da&&(this.da.disconnect(),this.da=null);this.G.disconnect();
this.G=null}V(){return this.u.V()}na(){return zb(this.u,this.ea)}pc(){return this.O.pc()}hb(){return this.O.hb()}oc(){return this.O.oc()}Ba(){return this.O.Ba()}U(){}mc(){}IsPlaying(){return!this.I&&!this.K&&!this.U()}Ma(){}fa(){return this.O.fa()}Play(){}Ca(){}jb(){}Jb(){}Oa(b){-1!==this.pb&&b>=this.pb&&(this.pb=-1,this.Rd&&this.Ca(),Cb(this.u,"fade-ended",this.ea,this.Pb))}qc(){const b=this.Ka;return isFinite(b)?b:0}Hb(){return this.u.Hb()}Ob(){}uc(){}Ea(){}tc(){}vc(){}rc(){}gb(){var b=this.Pb,
a=this.ea,c=this.fa(),d=this.Ka,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.Xa,orient:this.Wa,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.qa}}else f=null;return{aiid:b,tag:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Ma(),playbackRate:this.la,uid:this.qa,bufferOriginalUrl:this.pc(),bufferUrl:"",bufferType:this.oc(),isMusic:this.Ba(),isLooping:this.X,isMuted:this.Sa,resumePosition:this.rc(),pan:f,stereoPan:this.da?this.Zc:null}}Ac(b){var a=b.playbackRate;
this.la!==a&&(this.la=a,this.Ea());Eb(this,b.isMuted)}};"use strict";
self.ie=class extends self.gd{constructor(b,a,c){super(b,a,c);this.O.Ab.connect(this.G);this.O.onended=()=>this.Cc()}j(){this.Ca();this.O.Ab.disconnect();super.j()}T(){return this.O.T()}Cc(){this.I=!0;this.qa=-1;Cb(this.u,"ended",this.ea,this.Pb)}U(){return this.T().ended}mc(){return this.I?!0:this.U()}Ma(){let b=this.T().currentTime;this.X||(b=Math.min(b,this.fa()));return b}Play(b,a,c){const d=this.T();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);U(this,a);d.muted&&(d.muted=!1);
if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.O.hb()}' to position '${c}': `,e)}this.u.Da(d);this.K=this.I=!1;this.X=b;this.la=1}Ca(){const b=this.T();b.paused||b.pause();this.u.Na(b);this.I=!0;this.K=!1;this.qa=-1}jb(){if(!(this.K||this.I||this.U())){var b=this.T();b.paused||b.pause();this.u.Na(b);this.K=!0}}Jb(){!this.K||this.I||this.U()||(this.u.Da(this.T()),this.K=!1)}Ob(){this.T().muted=this.Sa||this.Hb()}uc(b){b=!!b;this.X!==b&&(this.X=
b,this.T().loop=b)}Ea(){let b=this.la;this.Uc&&(b*=this.u.jc);try{this.T().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}tc(b){if(!this.I&&!this.U())try{this.T().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}rc(){return this.Ma()}vc(b){b?this.IsPlaying()?(this.T().pause(),this.ta=!0):this.ta=!1:this.ta&&(this.u.Da(this.T()),this.ta=!1)}};"use strict";function W(b){b.o&&b.o.disconnect();b.o=null;b.kb=null}
self.ke=class extends self.gd{constructor(b,a,c){super(b,a,c);this.o=null;this.ac=d=>this.Cc(d);this.Pc=!0;this.kb=null;this.P=this.bc=this.dc=0;this.Xc=1}j(){this.Ca();W(this);this.ac=null;super.j()}Cc(b){this.K||this.ta||b.target!==this.kb||(this.I=this.Pc=!0,this.qa=-1,W(this),Cb(this.u,"ended",this.ea,this.Pb))}U(){return!this.I&&this.o&&this.o.loop||this.K?!1:this.Pc}mc(){return!this.o||this.I?!0:this.U()}Ma(){let b;b=this.K?this.P:this.bc+(V(this)-this.dc)*this.la;this.X||(b=Math.min(b,this.fa()));
return b}Play(b,a,c,d){this.Xc=1;U(this,a);W(this);this.o=this.V().createBufferSource();this.o.buffer=this.O.ha;this.o.connect(this.G);this.kb=this.o;this.o.onended=this.ac;this.o.loop=b;this.o.start(d,c);this.K=this.I=this.Pc=!1;this.X=b;this.la=1;this.dc=V(this);this.bc=c}Ca(){if(this.o)try{this.o.stop(0)}catch(b){}this.I=!0;this.K=!1;this.qa=-1}jb(){this.K||this.I||this.U()||(this.P=this.Ma(),this.X&&(this.P%=this.fa()),this.K=!0,this.o.stop(0))}Jb(){!this.K||this.I||this.U()||(W(this),this.o=
this.V().createBufferSource(),this.o.buffer=this.O.ha,this.o.connect(this.G),this.kb=this.o,this.o.onended=this.ac,this.o.loop=this.X,U(this,this.Ka),this.Ea(),this.o.start(0,this.P),this.dc=V(this),this.bc=this.P,this.K=!1)}qc(){return super.qc()*this.Xc}Ob(){this.Xc=this.Sa||this.Hb()?0:1;U(this,this.Ka)}uc(b){b=!!b;this.X!==b&&(this.X=b,this.o&&(this.o.loop=b))}Ea(){let b=this.la;this.Uc&&(b*=this.u.jc);this.o&&(this.o.playbackRate.value=b)}tc(b){this.I||this.U()||(this.K?this.P=b:(this.jb(),this.P=
b,this.Jb()))}rc(){return this.P}vc(b){b?this.IsPlaying()?(this.ta=!0,this.P=this.Ma(),this.X&&(this.P%=this.fa()),this.o.stop(0)):this.ta=!1:this.ta&&(W(this),this.o=this.V().createBufferSource(),this.o.buffer=this.O.ha,this.o.connect(this.G),this.kb=this.o,this.o.onended=this.ac,this.o.loop=this.X,U(this,this.Ka),this.Ea(),this.o.start(0,this.P),this.dc=V(this),this.bc=this.P,this.ta=!1)}Ac(b){super.Ac(b);this.P=b.resumePosition}};"use strict";function X(b){return b.g.createGain()}
function Y(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Z{constructor(b){this.u=b;this.g=b.V();this.Fd=-1;this.R=this.ea="";this.m=null}j(){this.g=null}N(){}S(){}gb(){return{type:this.R,tag:this.ea,params:this.m}}}
self.ae=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.R="filter";this.m=[a,c,d,e,f,g];this.v=X(this);this.i=X(this);this.i.gain.value=g;this.h=X(this);this.h.gain.value=1-g;this.C=this.g.createBiquadFilter();this.C.type=a;this.C.frequency.value=c;this.C.detune.value=d;this.C.Q.value=e;this.C.gain.vlaue=f;this.v.connect(this.C);this.v.connect(this.h);this.C.connect(this.i)}j(){this.v.disconnect();this.C.disconnect();this.i.disconnect();this.h.disconnect();super.j()}S(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 1:this.m[1]=a;Y(this,this.C.frequency,a,c,d);break;case 2:this.m[2]=a;Y(this,this.C.detune,a,c,d);break;case 3:this.m[3]=a;Y(this,this.C.Q,a,c,d);break;case 4:this.m[4]=a,Y(this,this.C.gain,a,c,d)}}};
self.Zd=class extends Z{constructor(b,a,c,d){super(b);this.R="delay";this.m=[a,c,d];this.v=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.xb=X(this);this.W=this.g.createDelay(a);this.W.delayTime.value=a;this.ob=X(this);this.ob.gain.value=c;this.v.connect(this.xb);this.v.connect(this.h);this.xb.connect(this.i);this.xb.connect(this.W);this.W.connect(this.ob);this.ob.connect(this.xb)}j(){this.v.disconnect();this.i.disconnect();this.h.disconnect();this.xb.disconnect();
this.W.disconnect();this.ob.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Y(b,a,c,d){const e=self.fb.jd;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[2]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 4:this.m[1]=e(a);Y(this,this.ob.gain,e(a),c,d);break;case 5:this.m[0]=a,Y(this,this.W.delayTime,a,c,d)}}};
self.Yd=class extends Z{constructor(b,a,c,d){super(b);this.R="convolution";this.m=[c,d];this.vd=this.ud="";this.v=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.nb=this.g.createConvolver();this.nb.normalize=c;this.nb.buffer=a;this.v.connect(this.nb);this.v.connect(this.h);this.nb.connect(this.i)}j(){this.v.disconnect();this.nb.disconnect();this.i.disconnect();this.h.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Y(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[1]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,1-a,c,d)}}gb(){const b=super.gb();b.bufferOriginalUrl=this.ud;b.bufferUrl="";b.bufferType=this.vd;return b}};
self.be=class extends Z{constructor(b,a,c,d,e,f){super(b);this.R="flanger";this.m=[a,c,d,e,f];this.v=X(this);this.h=X(this);this.h.gain.value=1-f/2;this.i=X(this);this.i.gain.value=f/2;this.qb=X(this);this.qb.gain.value=e;this.W=this.g.createDelay(a+c);this.W.delayTime.value=a;this.B=this.g.createOscillator();this.B.frequency.value=d;this.L=X(this);this.L.gain.value=c;this.v.connect(this.W);this.v.connect(this.h);this.W.connect(this.i);this.W.connect(this.qb);this.qb.connect(this.W);this.B.connect(this.L);
this.L.connect(this.W.delayTime);this.B.start(0)}j(){this.B.stop(0);this.v.disconnect();this.W.disconnect();this.B.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();this.qb.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[4]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 6:this.m[1]=a/1E3;Y(this,this.L.gain,a/1E3,
c,d);break;case 7:this.m[2]=a;Y(this,this.B.frequency,a,c,d);break;case 8:this.m[3]=a/100,Y(this,this.qb.gain,a/100,c,d)}}};
self.de=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.R="phaser";this.m=[a,c,d,e,f,g];this.v=X(this);this.h=X(this);this.h.gain.value=1-g/2;this.i=X(this);this.i.gain.value=g/2;this.C=this.g.createBiquadFilter();this.C.type="allpass";this.C.frequency.value=a;this.C.detune.value=c;this.C.Q.value=d;this.B=this.g.createOscillator();this.B.frequency.value=f;this.L=X(this);this.L.gain.value=e;this.v.connect(this.C);this.v.connect(this.h);this.C.connect(this.i);this.B.connect(this.L);this.L.connect(this.C.frequency);
this.B.start(0)}j(){this.B.stop(0);this.v.disconnect();this.C.disconnect();this.B.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 1:this.m[0]=a;Y(this,this.C.frequency,a,c,d);break;case 2:this.m[1]=a;Y(this,this.C.detune,a,c,d);
break;case 3:this.m[2]=a;Y(this,this.C.Q,a,c,d);break;case 6:this.m[3]=a;Y(this,this.L.gain,a,c,d);break;case 7:this.m[4]=a,Y(this,this.B.frequency,a,c,d)}}};self.ce=class extends Z{constructor(b,a){super(b);this.R="gain";this.m=[a];this.l=X(this);this.l.gain.value=a}j(){this.l.disconnect();super.j()}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Y(b,a,c,d){const e=self.fb.jd;switch(b){case 4:this.m[0]=e(a),Y(this,this.l.gain,e(a),c,d)}}};
self.fe=class extends Z{constructor(b,a){super(b);this.R="stereopan";this.m=[a];this.l=this.g.createStereoPanner();this.l.pan.value=a}j(){this.l.disconnect();super.j()}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Y(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.m[0]=a,Y(this,this.l.pan,a,c,d)}}};
self.ge=class extends Z{constructor(b,a,c){super(b);this.R="tremolo";this.m=[a,c];this.l=X(this);this.l.gain.value=1-c/2;this.B=this.g.createOscillator();this.B.frequency.value=a;this.L=X(this);this.L.gain.value=c/2;this.B.connect(this.L);this.L.connect(this.l.gain);this.B.start(0)}j(){this.B.stop(0);this.B.disconnect();this.L.disconnect();this.l.disconnect();super.j()}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=
a;Y(this,this.l.gain,1-a/2,c,d);Y(this,this.L.gain,a/2,c,d);break;case 7:this.m[0]=a,Y(this,this.B.frequency,a,c,d)}}};
self.ee=class extends Z{constructor(b,a,c){super(b);this.R="ringmod";this.m=[a,c];this.v=X(this);this.i=X(this);this.i.gain.value=c;this.h=X(this);this.h.gain.value=1-c;this.Db=X(this);this.Db.gain.value=0;this.B=this.g.createOscillator();this.B.frequency.value=a;this.B.connect(this.Db.gain);this.B.start(0);this.v.connect(this.Db);this.v.connect(this.h);this.Db.connect(this.i)}j(){this.B.stop(0);this.B.disconnect();this.Db.disconnect();this.v.disconnect();this.i.disconnect();this.h.disconnect();super.j()}S(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 7:this.m[0]=a,Y(this,this.B.frequency,a,c,d)}}};
self.$d=class extends Z{constructor(b,a,c,d,e,f){super(b);this.R="distortion";this.m=[a,c,d,e,f];this.v=X(this);this.ic=X(this);this.hc=X(this);b=d;.01>b&&(b=.01);this.ic.gain.value=b;this.hc.gain.value=Math.pow(1/b,.6)*e;this.i=X(this);this.i.gain.value=f;this.h=X(this);this.h.gain.value=1-f;this.kc=this.g.createWaveShaper();this.Lc=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Lc[32768+e]=f,this.Lc[32768-
e-1]=-f;this.kc.curve=this.Lc;this.v.connect(this.ic);this.v.connect(this.h);this.ic.connect(this.kc);this.kc.connect(this.hc);this.hc.connect(this.i)}j(){this.v.disconnect();this.ic.disconnect();this.kc.disconnect();this.hc.disconnect();this.i.disconnect();this.h.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[4]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,
1-a,c,d)}}};self.Xd=class extends Z{constructor(b,a,c,d,e,f){super(b);this.R="compressor";this.m=[a,c,d,e,f];this.l=this.g.createDynamicsCompressor();this.l.threshold.value=a;this.l.knee.value=c;this.l.ratio.value=d;this.l.attack.value=e;this.l.release.value=f}j(){this.l.disconnect();super.j()}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Y(){}};
self.Wd=class extends Z{constructor(b,a,c){super(b);this.R="analyser";this.m=[a,c];this.l=this.g.createAnalyser();this.l.fftSize=a;this.l.smoothingTimeConstant=c;this.Cd=new Float32Array(this.l.frequencyBinCount);this.Qd=new Uint8Array(a);this.Od=this.Ya=0;b=this.u;b.Qa.add(this);T(b)}j(){this.u.Qa.delete(this);this.l.disconnect();super.j()}Oa(){this.l.getFloatFrequencyData(this.Cd);this.l.getByteTimeDomainData(this.Qd);const b=this.l.fftSize;let a=this.Ya=0;for(var c=0;c<b;++c){let d=(this.Qd[c]-
128)/128;0>d&&(d=-d);this.Ya<d&&(this.Ya=d);a+=d*d}c=self.fb.re;this.Ya=c(this.Ya);this.Od=c(Math.sqrt(a/b))}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Y(){}};"use strict";function Ib(){}function Jb(b){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>k(b,"sw-message",a.data))}
function Kb(b){b=b.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}
self.oa.La(class extends self.Aa{constructor(b){super(b,"browser");this.A="";t(this,[["get-initial-state",a=>this.Dc(a)],["ready-for-sw-messages",()=>Jb(this)],["alert",a=>this.Bc(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Ec(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>Kb(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?
screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var c=a.type;if("back"===c)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===c)window.history.forward();else if("reload"===c)location.reload();else if("url"===
c){c=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):"preview"===a||"windows-webview2"===a?window.open(c,"_blank"):this.mf||(2===d?window.top.location=c:1===d?window.parent.location=c:window.location=c)}else"new-window"===c&&(c=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):window.open(c,a))}],["request-fullscreen",a=>{if("windows-webview2"===this.A||"macos-wkwebview"===this.A)self.oa.Nb(!0),
this.s.Hc({type:"set-fullscreen",fullscreen:!0});else{const c={navigationUI:"auto"};a=a.navUI;1===a?c.navigationUI="hide":2===a&&(c.navigationUI="show");a=document.documentElement;let d;a.requestFullscreen?d=a.requestFullscreen(c):a.mozRequestFullScreen?d=a.mozRequestFullScreen(c):a.msRequestFullscreen?d=a.msRequestFullscreen(c):a.webkitRequestFullScreen&&(d="undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen());d instanceof
Promise&&d.catch(Ib)}}],["exit-fullscreen",()=>{if("windows-webview2"===this.A||"macos-wkwebview"===this.A)self.oa.Nb(!1),this.s.Hc({type:"set-fullscreen",fullscreen:!1});else{let a;document.exitFullscreen?a=document.exitFullscreen():document.mozCancelFullScreen?a=document.mozCancelFullScreen():document.msExitFullscreen?a=document.msExitFullscreen():document.webkitCancelFullScreen&&(a=document.webkitCancelFullScreen());a instanceof Promise&&a.catch(Ib)}}],["set-hash",a=>{location.hash=a.hash}],["set-document-css-style",
a=>{const c=a.prop,d=a.value;var e=a.selector;a=a["is-all"];try{if(e)if(a)var f=Array.from(document.querySelectorAll(e));else{var g=document.querySelector(e);f=g?[g]:[]}else f=[document.documentElement];e=f;for(const h of e)c.startsWith("--")?h.style.setProperty(c,d):h.style[c]=d}catch(h){console.warn("[Browser] Failed to set style: ",h)}}],["get-document-css-style",a=>{{const d=a.prop;a=a.selector;try{const e=document.querySelector(a);var c=e?{isOk:!0,result:window.getComputedStyle(e).getPropertyValue(d)}:
{isOk:!1}}catch(e){console.warn("[Browser] Failed to get style: ",e),c={isOk:!1}}}return c}]]);window.addEventListener("online",()=>{k(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{k(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{k(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{k(this,"backbutton")})}Dc(b){this.A=b.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,
referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}Bc(b){alert(b.message)}Ec(b){b=b.isFocus;if("nwjs"===this.A){const a="nwjs"===this.A?nw.Window.get():null;b?a.focus():a.blur()}else b?window.focus():window.blur()}});"use strict";
self.oa.La(class extends self.Aa{constructor(b){super(b,"mouse");t(this,[["cursor",a=>{document.documentElement.style.cursor=a}],["request-pointer-lock",()=>{this.s.H.requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{k(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{k(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
"use strict";async function Lb(b){if(!b.Ia)try{b.Ia=await navigator.wakeLock.request("screen"),b.Ia.addEventListener("release",()=>{console.log("[Construct] Screen wake lock released");b.Ia=null;k(b,"wake-lock-released")}),console.log("[Construct] Screen wake lock acquired"),k(b,"wake-lock-acquired")}catch(a){console.warn("[Construct] Failed to acquire screen wake lock: ",a),k(b,"wake-lock-error")}}
function Mb(){var b=document.body;const a=b.style;a.setProperty("--temp-sai-top","env(safe-area-inset-top)");a.setProperty("--temp-sai-right","env(safe-area-inset-right)");a.setProperty("--temp-sai-bottom","env(safe-area-inset-bottom)");a.setProperty("--temp-sai-left","env(safe-area-inset-left)");b=getComputedStyle(b);b=[b.getPropertyValue("--temp-sai-top"),b.getPropertyValue("--temp-sai-right"),b.getPropertyValue("--temp-sai-bottom"),b.getPropertyValue("--temp-sai-left")].map(c=>{c=parseInt(c,10);
return isFinite(c)?c:0});a.removeProperty("--temp-sai-top");a.removeProperty("--temp-sai-right");a.removeProperty("--temp-sai-bottom");a.removeProperty("--temp-sai-left");return b}
self.oa.La(class extends self.Aa{constructor(b){super(b,"platform-info");t(this,[["get-initial-state",()=>this.Dc()],["request-wake-lock",()=>Lb(this)],["release-wake-lock",()=>{this.Ia&&(this.Ia.release(),this.Ia=null)}]]);window.addEventListener("resize",()=>{k(this,"window-resize",{windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,safeAreaInset:Mb()})});this.Ia=null}Dc(){return{screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,
safeAreaInset:Mb(),supportsWakeLock:!!navigator.wakeLock}}});"use strict";async function Nb(b,a){a=a.type;let c=!0;0===a?c=await Ob():1===a&&(c=await Pb());k(b,"permission-result",{type:a,result:c})}async function Ob(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function Pb(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.oa.La(class extends self.Aa{constructor(b){super(b,"touch");n(this,"request-permission",a=>Nb(this,a))}});
